### ISSUE TITLE
extlib version updates for perl 5.40

### ISSUE THREAD

**Issue by shawnlaffan** [StrawberryPerl/build-extlibs#55]
With Perl 5.40 coming soon it is time to update the external libs.  

Below is a list of libs that could be updated, using the MSYS2 package list as an indicator.  There might be more recent versions but we know we can adapt the MSYS2 patches, thus making the builds more efficient.  

If anyone knows of associated build issues with perl modules then please note them.

(Edit - libs that have been checked off pass the build process.  A branch with relevant changes is pending).  

- [x] gmp-6.3
- [x] mpfr-4.2.1
- [x] bzip-1.0.8
- [x] zlib-1.3.1
- [x] xz-5.4.6 (was originally xz-5.6.1 but that release had known issues)
- [x] expat-2.6.2
- [x] libxml2-2.12.6
- [x] libxslt-1.1.39
- [x] openssl-3.3.0  #53 
- [x] libssh2-1.11.0  (fails one test but it is a known issue: https://github.com/libssh2/libssh2/commit/572c57c9d8d4e89cfce19dde40125d55481256d1) 
- [x] postgresql-16.2 #36
- [x] giflib-5.2.2
- [x] tiff-4.6.0
- [x] libpng-1.6.43
- [x] graphite2-1.3.14
- [x] fribidi-1.0.14
- [x] freetype-2.13.2  (builds without harfbuz, but not with it)
- [x] harfbuzz-8.4.0  build issues: #56
- [x] fontconfig-2.15.0
- [x] libffi-3.4.6
- [x] libuv-1.48.0
- [x] libunistring-1.2
- [x] libidn2-2.3.7
- [x] lapack-3.12
- [x] fftw-3.3.10
- [x] gsl-2.7.1 - ~need to grab~ grabbed changes from #58 (also fails one set of sparse matrix tests but this is a known issue: https://stackoverflow.com/questions/61384846/gsl-on-windows-cant-find-header-files).  
- [x] plplot-5.15.0
- [x] hdf4-4.3.0 - tarball has code under ```./hdfsrc```.  ~Need to update the code to handle it or repack ourselves.~ (Done now)
- [x] netcdf-4.9.2 (one set of tests failing - see #57)
- [x] gnuplot-6.0.0
- [x] libwebp-1.4.0 #52

**Comment by shawnlaffan** [comment]
Remaining tasks:

- [ ] Package the postgresql ```initdb``` utility.  This is needed for more recent versions of DBD::pg.  Edit - initial efforts to get it to work were unsuccessful 
- [x] ~Patch OpenSSL3, per #53~ (punting for now)
- [x] Add the xz-5.4.6 zip archive to the release (the 5.40-RC1 build used a local version)

**Comment by shawnlaffan** [comment]
Closing this issue.  The postgres `initdb` builds are now being tracked under #69.
